package autoparams.internal.reflect;

import java.beans.ConstructorProperties;
import java.lang.reflect.Constructor;
import java.lang.reflect.Executable;
import java.lang.reflect.Parameter;
import java.util.Optional;

import static java.lang.System.lineSeparator;

/**
 * Internal utility for resolving parameter names. Not safe for
 * external use as its interface and behavior can change at any
 * time.
 */
public final class Parameters {

    private Parameters() {
    }

    /**
     * Returns the parameter name if available.
     *
     * @param parameter the parameter to resolve the name for
     * @param index     the index of the parameter
     * @return an {@link Optional} containing the name, or empty
     */
    public static Optional<String> getParameterName(
        Parameter parameter,
        int index
    ) {
        if (parameter.isNamePresent()) {
            return Optional.of(parameter.getName());
        }

        Executable executable = parameter.getDeclaringExecutable();
        if (executable instanceof Constructor) {
            ConstructorProperties properties = executable
                .getDeclaredAnnotation(ConstructorProperties.class);
            if (properties != null) {
                return Optional.of(properties.value()[index]);
            }
        }

        return Optional.empty();
    }

    /**
     * Returns the parameter name or throws if unavailable.
     *
     * @param parameter the parameter to resolve the name for
     * @param index     the index of the parameter
     * @return the parameter name
     * @throws RuntimeException if the name cannot be determined
     */
    public static String getRequiredParameterName(
        Parameter parameter,
        int index
    ) {
        return getParameterName(parameter, index).orElseThrow(() -> {
            String message = String.format(
                "Unable to determine the parameter name"
                    + " at index %d of executable %s."
                    + lineSeparator()
                    + lineSeparator()
                    + "Some features require parameter names"
                    + " to be available at runtime. However,"
                    + " Java does not include parameter names"
                    + " in bytecode by default."
                    + " To ensure this works correctly, you can:"
                    + lineSeparator()
                    + lineSeparator()
                    + "1. Use a record class, which preserves"
                    + " parameter names by design."
                    + lineSeparator()
                    + "2. Compile the code with the -parameters"
                    + " option using javac,"
                    + " or the -java-parameters option"
                    + " when using kotlinc."
                    + lineSeparator()
                    + "   If you're using Spring Boot,"
                    + " this option is automatically enabled"
                    + " when using the Spring Boot Gradle plugin"
                    + "(https://docs.spring.io/spring-boot/"
                    + "gradle-plugin/reacting.html"
                    + "#reacting-to-other-plugins.java)"
                    + " or the Spring Boot Maven plugin"
                    + "(https://docs.spring.io/spring-boot/"
                    + "maven-plugin/using.html)."
                    + lineSeparator()
                    + "3. Apply the @ConstructorProperties"
                    + " annotation to constructors to explicitly"
                    + " declare parameter names."
                    + " This annotation does not work"
                    + " for regular methods."
                    + lineSeparator()
                    + "   If you're using Lombok and the"
                    + " constructor is generated by a Lombok"
                    + " annotation such as @AllArgsConstructor,"
                    + " the annotation can be added automatically"
                    + " by enabling the"
                    + " 'lombok.anyConstructor"
                    + ".addConstructorProperties = true' option."
                    + lineSeparator()
                    + "   For more details, see:"
                    + " https://projectlombok.org"
                    + "/features/constructor",
                index,
                parameter.getDeclaringExecutable()
            );
            return new RuntimeException(message);
        });
    }
}
